import type { Metadata } from "next";
import {Inter, Poppins, Montserrat} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer/page";

const inter = Inter({subsets:["latin"]});
const poppins = Poppins({
 subsets:['latin'],
 weight:['400', '700']
});
const montserrat= Montserrat({subsets:['latin'],})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={poppins.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
